#!/usr/bin/env sh
echo "Running pre-commit checks..."

# Run Biome format and check, then add changes
npx bun run format
npx bun run lint
git add .

# Run typecheck
npx bun run typecheck

echo "Pre-commit checks completed."
